import{a as x,S as L,i as a}from"./assets/vendor-B-D547pe.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const d=async(o,t)=>(await x.get("https://pixabay.com/api/",{params:{key:"49241808-b19f3ed80577ae196aabc5d53",image_type:"photo",orientation:"horizontal",safesearch:"true",q:o,per_page:15,page:t}})).data,l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEZSURBVHgBrZVRDoMgDIar0fi6m2xH2Y3Ek2w3cFfZXXwBljFQCai0xemfoCaU/xNpKwAirXWrlDY5w8ViPhVmbgwIO14A3zeQKq/2IuwaqOu6A07+zaVUT8iUi+V28rd5NuSIOQs5wxyFUOZKqRtnmIpZQCZz3acWcgcXUjkF0b2bmwFSpAxskMAgYecaWSsFC8AgnHkMqIBR09TCGrnHsZic5iLs3By3ngWsITMgy9yphEyVJZjUM6esHUS9yfea7N7DAmJz/1niM2EhVBZR2UKl8DS/SFO80OhUnCBkoYWgz2MdNAx8q0jFOK/Fy1GQvdqYe50BQc3PgLDmRyCU+aYOfFsoCtPa+yXvp2/ue9rHqLATflCf5QflVUcNIrzeSwAAAABJRU5ErkJggg==",S=document.querySelector(".gallery"),F=document.querySelector(".loadMore-btn"),p=new L(".gallery a",{captionsData:"alt",captionDelay:250}),h=({hits:o,totalHits:t})=>{const r=[];o.forEach(n=>{const{webformatURL:e,largeImageURL:s,tags:c,likes:u,views:y,comments:A,downloads:f}=n;r.push(`<li class="gallery-item">
         <a class="gallery-link" href="${s}">
           <img
             class="gallery-image"
             src="${e}"
             alt="${c}"
           />
           <ul class="desc">
               <li class="descel"><span class="bold">Likes:</span> ${u}</li>
               <li class="descel"><span class="bold">Views:</span> ${y}</li>
               <li class="descel"><span class="bold">Comments:</span> ${A}</li>
               <li class="descel"><span class="bold">Downloads:</span> ${f}</li>
             </ul>
         </a>
       </li>`)}),S.insertAdjacentHTML("beforeend",r.join("")),p.refresh(),o.length===15?F.dataset.visible="true":(t<=15||a.show({title:"😢",message:"We're sorry, but you've reached the end of search results.",color:"#a4ccb1",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"}),F.dataset.visible="false")},C=document.querySelector(".form"),m=document.querySelector("[name=search-text]"),w=document.querySelector(".gallery"),i=document.querySelector(".loader");i.classList.remove("loader");C.addEventListener("submit",async o=>{if(o.preventDefault(),w.innerHTML="",i.classList.toggle("loader"),F.dataset.visible="false",m.value.trim().length===0){i.classList.remove("loader"),a.show({title:"Error",message:"Please enter your request",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}g=1;try{const{hits:t,totalHits:r}=await d(m.value,g);if(i.classList.remove("loader"),t.length===0){a.show({title:"😢",message:"Sorry, there are no images matching your search query. Please try again!",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}h({hits:t,totalHits:r}),p.refresh()}catch(t){i.classList.remove("loader"),a.show({title:"😢",message:t.message,color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"})}});let g=1;F.addEventListener("click",async o=>{o.preventDefault(),g++;try{const{hits:t,totalHits:r}=await d(m.value,g);if(i.classList.remove("loader"),t.length===0){a.show({title:"😢",message:"Sorry, there are no images matching your search query. Please try again!",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}await h({hits:t,totalHits:r}),p.refresh();const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:-e.y*2,behavior:"smooth"})}catch(t){i.classList.remove("loader"),a.show({title:"😢",message:t.message,color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"})}});
//# sourceMappingURL=index.js.map
