import{a as u,S as A,i as n}from"./assets/vendor-B-D547pe.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function l(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=l(e);fetch(e.href,s)}})();const h=async r=>(await u.get("https://pixabay.com/api/",{params:{key:"49241808-b19f3ed80577ae196aabc5d53",image_type:"photo",orientation:"horizontal",safesearch:"true",q:r}})).data.hits,g=document.querySelector(".gallery"),f=new A(".gallery a",{captionsData:"alt",captionDelay:250}),y=r=>{g.innerHTML="";const t=[];r.forEach(l=>{const{webformatURL:a,largeImageURL:e,tags:s,likes:o,views:F,comments:d,downloads:p}=l;return t.push(`<li class="gallery-item">
         <a class="gallery-link" href="${e}">
           <img
             class="gallery-image"
             src="${a}"
             alt="${s}"
           />
           <ul class="desc">
               <li class="descel"><span class="bold">Likes:</span> ${o}</li>
               <li class="descel"><span class="bold">Views:</span> ${F}</li>
               <li class="descel"><span class="bold">Comments:</span> ${d}</li>
               <li class="descel"><span class="bold">Downloads:</span> ${p}</li>
             </ul>
         </a>
       </li>`)}),g.insertAdjacentHTML("beforeend",t.join(""))},c="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEZSURBVHgBrZVRDoMgDIar0fi6m2xH2Y3Ek2w3cFfZXXwBljFQCai0xemfoCaU/xNpKwAirXWrlDY5w8ViPhVmbgwIO14A3zeQKq/2IuwaqOu6A07+zaVUT8iUi+V28rd5NuSIOQs5wxyFUOZKqRtnmIpZQCZz3acWcgcXUjkF0b2bmwFSpAxskMAgYecaWSsFC8AgnHkMqIBR09TCGrnHsZic5iLs3By3ngWsITMgy9yphEyVJZjUM6esHUS9yfea7N7DAmJz/1niM2EhVBZR2UKl8DS/SFO80OhUnCBkoYWgz2MdNAx8q0jFOK/Fy1GQvdqYe50BQc3PgLDmRyCU+aYOfFsoCtPa+yXvp2/ue9rHqLATflCf5QflVUcNIrzeSwAAAABJRU5ErkJggg==",L=document.querySelector(".form"),m=document.querySelector("[name=search-text]"),w=document.querySelector(".gallery"),i=document.querySelector(".loader");i.classList.remove("loader");L.addEventListener("submit",async r=>{r.preventDefault(),w.innerHTML="",i.classList.toggle("loader"),m.value.trim().length===0&&(i.classList.remove("loader"),n.show({title:"Error",message:"Please enter your request",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:c,iconColor:"#FFFFFF",theme:"dark",position:"topRight"}),returnж);try{const t=await h(m.value);if(i.classList.remove("loader"),t.length===0){n.show({title:"😢",message:"Sorry, there are no images matching your search query. Please try again!",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:c,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}y(t),f.refresh()}catch(t){i.classList.remove("loader"),n.show({title:"😢",message:t.message,color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:c,iconColor:"#FFFFFF",theme:"dark",position:"topRight"})}});
//# sourceMappingURL=index.js.map
