import{a as f,S as x,i as a}from"./assets/vendor-B-D547pe.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const m=async(s,e)=>(await f.get("https://pixabay.com/api/",{params:{key:"49241808-b19f3ed80577ae196aabc5d53",image_type:"photo",orientation:"horizontal",safesearch:"true",q:s,per_page:15,page:e}})).data.hits,l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEZSURBVHgBrZVRDoMgDIar0fi6m2xH2Y3Ek2w3cFfZXXwBljFQCai0xemfoCaU/xNpKwAirXWrlDY5w8ViPhVmbgwIO14A3zeQKq/2IuwaqOu6A07+zaVUT8iUi+V28rd5NuSIOQs5wxyFUOZKqRtnmIpZQCZz3acWcgcXUjkF0b2bmwFSpAxskMAgYecaWSsFC8AgnHkMqIBR09TCGrnHsZic5iLs3By3ngWsITMgy9yphEyVJZjUM6esHUS9yfea7N7DAmJz/1niM2EhVBZR2UKl8DS/SFO80OhUnCBkoYWgz2MdNAx8q0jFOK/Fy1GQvdqYe50BQc3PgLDmRyCU+aYOfFsoCtPa+yXvp2/ue9rHqLATflCf5QflVUcNIrzeSwAAAABJRU5ErkJggg==",L=document.querySelector(".gallery"),p=document.querySelector(".loadMore-btn"),d=new x(".gallery a",{captionsData:"alt",captionDelay:250}),h=s=>{const e=[];s.forEach(n=>{const{webformatURL:i,largeImageURL:t,tags:o,likes:c,views:u,comments:y,downloads:A}=n;return e.push(`<li class="gallery-item">
         <a class="gallery-link" href="${t}">
           <img
             class="gallery-image"
             src="${i}"
             alt="${o}"
           />
           <ul class="desc">
               <li class="descel"><span class="bold">Likes:</span> ${c}</li>
               <li class="descel"><span class="bold">Views:</span> ${u}</li>
               <li class="descel"><span class="bold">Comments:</span> ${y}</li>
               <li class="descel"><span class="bold">Downloads:</span> ${A}</li>
             </ul>
         </a>
       </li>`)}),L.insertAdjacentHTML("beforeend",e.join("")),s.length===15?p.dataset.visible="true":a.show({title:"😢",message:"We're sorry, but you've reached the end of search results.",color:"#a4ccb1",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"})},S=document.querySelector(".form"),F=document.querySelector("[name=search-text]"),C=document.querySelector(".gallery"),r=document.querySelector(".loader");r.classList.remove("loader");S.addEventListener("submit",async s=>{if(s.preventDefault(),C.innerHTML="",r.classList.toggle("loader"),F.value.trim().length===0){r.classList.remove("loader"),a.show({title:"Error",message:"Please enter your request",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}try{const e=await m(F.value);if(r.classList.remove("loader"),e.length===0){a.show({title:"😢",message:"Sorry, there are no images matching your search query. Please try again!",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}h(e),d.refresh()}catch(e){r.classList.remove("loader"),a.show({title:"😢",message:e.message,color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"})}});let g=1;p.addEventListener("click",async s=>{s.preventDefault(),g++;try{const e=await m(F.value,g);if(r.classList.remove("loader"),e.length===0){a.show({title:"😢",message:"Sorry, there are no images matching your search query. Please try again!",color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"});return}await h(e),d.refresh();const i=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:-i.y*2,behavior:"smooth"})}catch(e){r.classList.remove("loader"),a.show({title:"😢",message:e.message,color:"#EF4040",titleColor:"#FFFFFF",titleSize:"16px",titleLineHeight:"24px",messageColor:"#FFFFFF",messageSize:"16px",messageLineHeight:"24px",iconUrl:l,iconColor:"#FFFFFF",theme:"dark",position:"topRight"})}});
//# sourceMappingURL=index.js.map
